# Changes here will be overwritten by Copier
_commit: a74894d
_src_path: https://github.com/python-project-templates/base.git
add_docs: false
add_extension: python
add_wiki: false
email: t.paine154@gmail.com
github: airflow-laminar
project_description: Supervisor operators and configuration for long-running tasks
project_name: airflow-supervisor
python_version_primary: '3.11'
team: the airflow-supervisor authors
